# This is a basic workflow to help you get started with Actions

name: Build Game

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "Deployment" ]
  pull_request:
    branches: [ "Deployment" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_project_WebGL:
    name: Build my project to WebGL ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Checkout web repo
        uses: actions/checkout@v2
        with:
          path: Website
          repository: EMC-Beta/Beta-dev-web-app
          lfs: true
          token: ${{ secrets.GHA_TOKEN }}    

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-WebGL
          restore-keys: |
            library-build
            Library-
      
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildsPath: Webstie/public/beta-app/prototype-3/
          
               # Checkout
          
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          cwd: './Website/'
          message: "Adding build [Add build version]"
